// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: links.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_links_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_links_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_links_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_links_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_links_2eproto;
namespace speech {
namespace sparrowhawk {
class Links;
struct LinksDefaultTypeInternal;
extern LinksDefaultTypeInternal _Links_default_instance_;
}  // namespace sparrowhawk
}  // namespace speech
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace speech {
namespace sparrowhawk {

// ===================================================================


// -------------------------------------------------------------------

class Links final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.Links) */ {
 public:
  inline Links() : Links(nullptr) {}
  ~Links() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Links(::google::protobuf::internal::ConstantInitialized);

  inline Links(const Links& from)
      : Links(nullptr, from) {}
  Links(Links&& from) noexcept
    : Links() {
    *this = ::std::move(from);
  }

  inline Links& operator=(const Links& from) {
    CopyFrom(from);
    return *this;
  }
  inline Links& operator=(Links&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Links& default_instance() {
    return *internal_default_instance();
  }
  static inline const Links* internal_default_instance() {
    return reinterpret_cast<const Links*>(
               &_Links_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Links& a, Links& b) {
    a.Swap(&b);
  }
  inline void Swap(Links* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Links* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Links* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Links>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Links& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Links& from) {
    Links::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Links* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.Links";
  }
  protected:
  explicit Links(::google::protobuf::Arena* arena);
  Links(::google::protobuf::Arena* arena, const Links& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOwnIndexFieldNumber = 1,
    kParentFieldNumber = 2,
    kFirstChildFieldNumber = 3,
    kLastChildFieldNumber = 4,
  };
  // optional int32 own_index = 1;
  bool has_own_index() const;
  void clear_own_index() ;
  ::int32_t own_index() const;
  void set_own_index(::int32_t value);

  private:
  ::int32_t _internal_own_index() const;
  void _internal_set_own_index(::int32_t value);

  public:
  // optional int32 parent = 2;
  bool has_parent() const;
  void clear_parent() ;
  ::int32_t parent() const;
  void set_parent(::int32_t value);

  private:
  ::int32_t _internal_parent() const;
  void _internal_set_parent(::int32_t value);

  public:
  // optional int32 first_child = 3;
  bool has_first_child() const;
  void clear_first_child() ;
  ::int32_t first_child() const;
  void set_first_child(::int32_t value);

  private:
  ::int32_t _internal_first_child() const;
  void _internal_set_first_child(::int32_t value);

  public:
  // optional int32 last_child = 4;
  bool has_last_child() const;
  void clear_last_child() ;
  ::int32_t last_child() const;
  void set_last_child(::int32_t value);

  private:
  ::int32_t _internal_last_child() const;
  void _internal_set_last_child(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.Links)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t own_index_;
    ::int32_t parent_;
    ::int32_t first_child_;
    ::int32_t last_child_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_links_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Links

// optional int32 own_index = 1;
inline bool Links::has_own_index() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Links::clear_own_index() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.own_index_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t Links::own_index() const {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Links.own_index)
  return _internal_own_index();
}
inline void Links::set_own_index(::int32_t value) {
  _internal_set_own_index(value);
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Links.own_index)
}
inline ::int32_t Links::_internal_own_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.own_index_;
}
inline void Links::_internal_set_own_index(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.own_index_ = value;
}

// optional int32 parent = 2;
inline bool Links::has_parent() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Links::clear_parent() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.parent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t Links::parent() const {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Links.parent)
  return _internal_parent();
}
inline void Links::set_parent(::int32_t value) {
  _internal_set_parent(value);
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Links.parent)
}
inline ::int32_t Links::_internal_parent() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.parent_;
}
inline void Links::_internal_set_parent(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.parent_ = value;
}

// optional int32 first_child = 3;
inline bool Links::has_first_child() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Links::clear_first_child() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.first_child_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t Links::first_child() const {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Links.first_child)
  return _internal_first_child();
}
inline void Links::set_first_child(::int32_t value) {
  _internal_set_first_child(value);
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Links.first_child)
}
inline ::int32_t Links::_internal_first_child() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.first_child_;
}
inline void Links::_internal_set_first_child(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.first_child_ = value;
}

// optional int32 last_child = 4;
inline bool Links::has_last_child() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Links::clear_last_child() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.last_child_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t Links::last_child() const {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Links.last_child)
  return _internal_last_child();
}
inline void Links::set_last_child(::int32_t value) {
  _internal_set_last_child(value);
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Links.last_child)
}
inline ::int32_t Links::_internal_last_child() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.last_child_;
}
inline void Links::_internal_set_last_child(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.last_child_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sparrowhawk
}  // namespace speech


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_links_2eproto_2epb_2eh
