// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rule_order.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_rule_5forder_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_rule_5forder_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rule_5forder_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rule_5forder_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_rule_5forder_2eproto;
namespace speech {
namespace sparrowhawk {
class Grammar;
struct GrammarDefaultTypeInternal;
extern GrammarDefaultTypeInternal _Grammar_default_instance_;
class Rule;
struct RuleDefaultTypeInternal;
extern RuleDefaultTypeInternal _Rule_default_instance_;
}  // namespace sparrowhawk
}  // namespace speech
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace speech {
namespace sparrowhawk {

// ===================================================================


// -------------------------------------------------------------------

class Rule final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.Rule) */ {
 public:
  inline Rule() : Rule(nullptr) {}
  ~Rule() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Rule(::google::protobuf::internal::ConstantInitialized);

  inline Rule(const Rule& from)
      : Rule(nullptr, from) {}
  Rule(Rule&& from) noexcept
    : Rule() {
    *this = ::std::move(from);
  }

  inline Rule& operator=(const Rule& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rule& operator=(Rule&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Rule& default_instance() {
    return *internal_default_instance();
  }
  static inline const Rule* internal_default_instance() {
    return reinterpret_cast<const Rule*>(
               &_Rule_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Rule& a, Rule& b) {
    a.Swap(&b);
  }
  inline void Swap(Rule* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rule* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Rule* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Rule>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Rule& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Rule& from) {
    Rule::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Rule* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.Rule";
  }
  protected:
  explicit Rule(::google::protobuf::Arena* arena);
  Rule(::google::protobuf::Arena* arena, const Rule& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMainFieldNumber = 1,
    kParensFieldNumber = 2,
    kAssignmentsFieldNumber = 3,
    kRedupFieldNumber = 4,
  };
  // required string main = 1;
  bool has_main() const;
  void clear_main() ;
  const std::string& main() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_main(Arg_&& arg, Args_... args);
  std::string* mutable_main();
  PROTOBUF_NODISCARD std::string* release_main();
  void set_allocated_main(std::string* value);

  private:
  const std::string& _internal_main() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_main(
      const std::string& value);
  std::string* _internal_mutable_main();

  public:
  // optional string parens = 2;
  bool has_parens() const;
  void clear_parens() ;
  const std::string& parens() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_parens(Arg_&& arg, Args_... args);
  std::string* mutable_parens();
  PROTOBUF_NODISCARD std::string* release_parens();
  void set_allocated_parens(std::string* value);

  private:
  const std::string& _internal_parens() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parens(
      const std::string& value);
  std::string* _internal_mutable_parens();

  public:
  // optional string assignments = 3;
  bool has_assignments() const;
  void clear_assignments() ;
  const std::string& assignments() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_assignments(Arg_&& arg, Args_... args);
  std::string* mutable_assignments();
  PROTOBUF_NODISCARD std::string* release_assignments();
  void set_allocated_assignments(std::string* value);

  private:
  const std::string& _internal_assignments() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_assignments(
      const std::string& value);
  std::string* _internal_mutable_assignments();

  public:
  // optional string redup = 4;
  bool has_redup() const;
  void clear_redup() ;
  const std::string& redup() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_redup(Arg_&& arg, Args_... args);
  std::string* mutable_redup();
  PROTOBUF_NODISCARD std::string* release_redup();
  void set_allocated_redup(std::string* value);

  private:
  const std::string& _internal_redup() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_redup(
      const std::string& value);
  std::string* _internal_mutable_redup();

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.Rule)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      58, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr main_;
    ::google::protobuf::internal::ArenaStringPtr parens_;
    ::google::protobuf::internal::ArenaStringPtr assignments_;
    ::google::protobuf::internal::ArenaStringPtr redup_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rule_5forder_2eproto;
};// -------------------------------------------------------------------

class Grammar final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.Grammar) */ {
 public:
  inline Grammar() : Grammar(nullptr) {}
  ~Grammar() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Grammar(::google::protobuf::internal::ConstantInitialized);

  inline Grammar(const Grammar& from)
      : Grammar(nullptr, from) {}
  Grammar(Grammar&& from) noexcept
    : Grammar() {
    *this = ::std::move(from);
  }

  inline Grammar& operator=(const Grammar& from) {
    CopyFrom(from);
    return *this;
  }
  inline Grammar& operator=(Grammar&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Grammar& default_instance() {
    return *internal_default_instance();
  }
  static inline const Grammar* internal_default_instance() {
    return reinterpret_cast<const Grammar*>(
               &_Grammar_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Grammar& a, Grammar& b) {
    a.Swap(&b);
  }
  inline void Swap(Grammar* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Grammar* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Grammar* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Grammar>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Grammar& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Grammar& from) {
    Grammar::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Grammar* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.Grammar";
  }
  protected:
  explicit Grammar(::google::protobuf::Arena* arena);
  Grammar(::google::protobuf::Arena* arena, const Grammar& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRulesFieldNumber = 3,
    kGrammarFileFieldNumber = 1,
    kGrammarNameFieldNumber = 2,
  };
  // repeated .speech.sparrowhawk.Rule rules = 3;
  int rules_size() const;
  private:
  int _internal_rules_size() const;

  public:
  void clear_rules() ;
  ::speech::sparrowhawk::Rule* mutable_rules(int index);
  ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::Rule >*
      mutable_rules();
  private:
  const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::Rule>& _internal_rules() const;
  ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::Rule>* _internal_mutable_rules();
  public:
  const ::speech::sparrowhawk::Rule& rules(int index) const;
  ::speech::sparrowhawk::Rule* add_rules();
  const ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::Rule >&
      rules() const;
  // required string grammar_file = 1;
  bool has_grammar_file() const;
  void clear_grammar_file() ;
  const std::string& grammar_file() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_grammar_file(Arg_&& arg, Args_... args);
  std::string* mutable_grammar_file();
  PROTOBUF_NODISCARD std::string* release_grammar_file();
  void set_allocated_grammar_file(std::string* value);

  private:
  const std::string& _internal_grammar_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_grammar_file(
      const std::string& value);
  std::string* _internal_mutable_grammar_file();

  public:
  // required string grammar_name = 2;
  bool has_grammar_name() const;
  void clear_grammar_name() ;
  const std::string& grammar_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_grammar_name(Arg_&& arg, Args_... args);
  std::string* mutable_grammar_name();
  PROTOBUF_NODISCARD std::string* release_grammar_name();
  void set_allocated_grammar_name(std::string* value);

  private:
  const std::string& _internal_grammar_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_grammar_name(
      const std::string& value);
  std::string* _internal_mutable_grammar_name();

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.Grammar)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      59, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::Rule > rules_;
    ::google::protobuf::internal::ArenaStringPtr grammar_file_;
    ::google::protobuf::internal::ArenaStringPtr grammar_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rule_5forder_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Rule

// required string main = 1;
inline bool Rule::has_main() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Rule::clear_main() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.main_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Rule::main() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Rule.main)
  return _internal_main();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Rule::set_main(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.main_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Rule.main)
}
inline std::string* Rule::mutable_main() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_main();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Rule.main)
  return _s;
}
inline const std::string& Rule::_internal_main() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.main_.Get();
}
inline void Rule::_internal_set_main(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.main_.Set(value, GetArena());
}
inline std::string* Rule::_internal_mutable_main() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.main_.Mutable( GetArena());
}
inline std::string* Rule::release_main() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.Rule.main)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.main_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.main_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Rule::set_allocated_main(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.main_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.main_.IsDefault()) {
          _impl_.main_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.Rule.main)
}

// optional string parens = 2;
inline bool Rule::has_parens() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Rule::clear_parens() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.parens_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Rule::parens() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Rule.parens)
  return _internal_parens();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Rule::set_parens(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.parens_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Rule.parens)
}
inline std::string* Rule::mutable_parens() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_parens();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Rule.parens)
  return _s;
}
inline const std::string& Rule::_internal_parens() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.parens_.Get();
}
inline void Rule::_internal_set_parens(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.parens_.Set(value, GetArena());
}
inline std::string* Rule::_internal_mutable_parens() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.parens_.Mutable( GetArena());
}
inline std::string* Rule::release_parens() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.Rule.parens)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.parens_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.parens_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Rule::set_allocated_parens(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.parens_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.parens_.IsDefault()) {
          _impl_.parens_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.Rule.parens)
}

// optional string assignments = 3;
inline bool Rule::has_assignments() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Rule::clear_assignments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.assignments_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Rule::assignments() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Rule.assignments)
  return _internal_assignments();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Rule::set_assignments(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.assignments_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Rule.assignments)
}
inline std::string* Rule::mutable_assignments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_assignments();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Rule.assignments)
  return _s;
}
inline const std::string& Rule::_internal_assignments() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.assignments_.Get();
}
inline void Rule::_internal_set_assignments(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.assignments_.Set(value, GetArena());
}
inline std::string* Rule::_internal_mutable_assignments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.assignments_.Mutable( GetArena());
}
inline std::string* Rule::release_assignments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.Rule.assignments)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.assignments_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.assignments_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Rule::set_allocated_assignments(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.assignments_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.assignments_.IsDefault()) {
          _impl_.assignments_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.Rule.assignments)
}

// optional string redup = 4;
inline bool Rule::has_redup() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Rule::clear_redup() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.redup_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Rule::redup() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Rule.redup)
  return _internal_redup();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Rule::set_redup(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.redup_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Rule.redup)
}
inline std::string* Rule::mutable_redup() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_redup();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Rule.redup)
  return _s;
}
inline const std::string& Rule::_internal_redup() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.redup_.Get();
}
inline void Rule::_internal_set_redup(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.redup_.Set(value, GetArena());
}
inline std::string* Rule::_internal_mutable_redup() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.redup_.Mutable( GetArena());
}
inline std::string* Rule::release_redup() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.Rule.redup)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.redup_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.redup_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Rule::set_allocated_redup(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.redup_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.redup_.IsDefault()) {
          _impl_.redup_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.Rule.redup)
}

// -------------------------------------------------------------------

// Grammar

// required string grammar_file = 1;
inline bool Grammar::has_grammar_file() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Grammar::clear_grammar_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.grammar_file_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Grammar::grammar_file() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Grammar.grammar_file)
  return _internal_grammar_file();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Grammar::set_grammar_file(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.grammar_file_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Grammar.grammar_file)
}
inline std::string* Grammar::mutable_grammar_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_grammar_file();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Grammar.grammar_file)
  return _s;
}
inline const std::string& Grammar::_internal_grammar_file() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.grammar_file_.Get();
}
inline void Grammar::_internal_set_grammar_file(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.grammar_file_.Set(value, GetArena());
}
inline std::string* Grammar::_internal_mutable_grammar_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.grammar_file_.Mutable( GetArena());
}
inline std::string* Grammar::release_grammar_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.Grammar.grammar_file)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.grammar_file_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.grammar_file_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Grammar::set_allocated_grammar_file(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.grammar_file_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.grammar_file_.IsDefault()) {
          _impl_.grammar_file_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.Grammar.grammar_file)
}

// required string grammar_name = 2;
inline bool Grammar::has_grammar_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Grammar::clear_grammar_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.grammar_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Grammar::grammar_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Grammar.grammar_name)
  return _internal_grammar_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Grammar::set_grammar_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.grammar_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.Grammar.grammar_name)
}
inline std::string* Grammar::mutable_grammar_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_grammar_name();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Grammar.grammar_name)
  return _s;
}
inline const std::string& Grammar::_internal_grammar_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.grammar_name_.Get();
}
inline void Grammar::_internal_set_grammar_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.grammar_name_.Set(value, GetArena());
}
inline std::string* Grammar::_internal_mutable_grammar_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.grammar_name_.Mutable( GetArena());
}
inline std::string* Grammar::release_grammar_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.Grammar.grammar_name)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.grammar_name_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.grammar_name_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Grammar::set_allocated_grammar_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.grammar_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.grammar_name_.IsDefault()) {
          _impl_.grammar_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.Grammar.grammar_name)
}

// repeated .speech.sparrowhawk.Rule rules = 3;
inline int Grammar::_internal_rules_size() const {
  return _internal_rules().size();
}
inline int Grammar::rules_size() const {
  return _internal_rules_size();
}
inline void Grammar::clear_rules() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rules_.Clear();
}
inline ::speech::sparrowhawk::Rule* Grammar::mutable_rules(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.Grammar.rules)
  return _internal_mutable_rules()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::Rule>* Grammar::mutable_rules()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.Grammar.rules)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_rules();
}
inline const ::speech::sparrowhawk::Rule& Grammar::rules(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.Grammar.rules)
  return _internal_rules().Get(index);
}
inline ::speech::sparrowhawk::Rule* Grammar::add_rules() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::speech::sparrowhawk::Rule* _add = _internal_mutable_rules()->Add();
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.Grammar.rules)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::Rule>& Grammar::rules() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.Grammar.rules)
  return _internal_rules();
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::Rule>&
Grammar::_internal_rules() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rules_;
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::Rule>*
Grammar::_internal_mutable_rules() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.rules_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sparrowhawk
}  // namespace speech


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_rule_5forder_2eproto_2epb_2eh
