// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_spec.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_serialization_5fspec_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_serialization_5fspec_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_serialization_5fspec_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_serialization_5fspec_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_serialization_5fspec_2eproto;
namespace speech {
namespace sparrowhawk {
class ClassSpec;
struct ClassSpecDefaultTypeInternal;
extern ClassSpecDefaultTypeInternal _ClassSpec_default_instance_;
class RecordSpec;
struct RecordSpecDefaultTypeInternal;
extern RecordSpecDefaultTypeInternal _RecordSpec_default_instance_;
class SerializeSpec;
struct SerializeSpecDefaultTypeInternal;
extern SerializeSpecDefaultTypeInternal _SerializeSpec_default_instance_;
class StyleSpec;
struct StyleSpecDefaultTypeInternal;
extern StyleSpecDefaultTypeInternal _StyleSpec_default_instance_;
}  // namespace sparrowhawk
}  // namespace speech
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace speech {
namespace sparrowhawk {

// ===================================================================


// -------------------------------------------------------------------

class RecordSpec final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.RecordSpec) */ {
 public:
  inline RecordSpec() : RecordSpec(nullptr) {}
  ~RecordSpec() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR RecordSpec(::google::protobuf::internal::ConstantInitialized);

  inline RecordSpec(const RecordSpec& from)
      : RecordSpec(nullptr, from) {}
  RecordSpec(RecordSpec&& from) noexcept
    : RecordSpec() {
    *this = ::std::move(from);
  }

  inline RecordSpec& operator=(const RecordSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecordSpec& operator=(RecordSpec&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecordSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecordSpec* internal_default_instance() {
    return reinterpret_cast<const RecordSpec*>(
               &_RecordSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RecordSpec& a, RecordSpec& b) {
    a.Swap(&b);
  }
  inline void Swap(RecordSpec* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecordSpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecordSpec* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecordSpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RecordSpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const RecordSpec& from) {
    RecordSpec::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(RecordSpec* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.RecordSpec";
  }
  protected:
  explicit RecordSpec(::google::protobuf::Arena* arena);
  RecordSpec(::google::protobuf::Arena* arena, const RecordSpec& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPrefixSpecFieldNumber = 1,
    kSuffixSpecFieldNumber = 2,
    kFieldPathFieldNumber = 3,
    kLabelFieldNumber = 4,
    kDefaultValueFieldNumber = 5,
  };
  // repeated .speech.sparrowhawk.RecordSpec prefix_spec = 1;
  int prefix_spec_size() const;
  private:
  int _internal_prefix_spec_size() const;

  public:
  void clear_prefix_spec() ;
  ::speech::sparrowhawk::RecordSpec* mutable_prefix_spec(int index);
  ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec >*
      mutable_prefix_spec();
  private:
  const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>& _internal_prefix_spec() const;
  ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>* _internal_mutable_prefix_spec();
  public:
  const ::speech::sparrowhawk::RecordSpec& prefix_spec(int index) const;
  ::speech::sparrowhawk::RecordSpec* add_prefix_spec();
  const ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec >&
      prefix_spec() const;
  // repeated .speech.sparrowhawk.RecordSpec suffix_spec = 2;
  int suffix_spec_size() const;
  private:
  int _internal_suffix_spec_size() const;

  public:
  void clear_suffix_spec() ;
  ::speech::sparrowhawk::RecordSpec* mutable_suffix_spec(int index);
  ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec >*
      mutable_suffix_spec();
  private:
  const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>& _internal_suffix_spec() const;
  ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>* _internal_mutable_suffix_spec();
  public:
  const ::speech::sparrowhawk::RecordSpec& suffix_spec(int index) const;
  ::speech::sparrowhawk::RecordSpec* add_suffix_spec();
  const ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec >&
      suffix_spec() const;
  // optional string field_path = 3;
  bool has_field_path() const;
  void clear_field_path() ;
  const std::string& field_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_field_path(Arg_&& arg, Args_... args);
  std::string* mutable_field_path();
  PROTOBUF_NODISCARD std::string* release_field_path();
  void set_allocated_field_path(std::string* value);

  private:
  const std::string& _internal_field_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_field_path(
      const std::string& value);
  std::string* _internal_mutable_field_path();

  public:
  // optional string label = 4;
  bool has_label() const;
  void clear_label() ;
  const std::string& label() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_label(Arg_&& arg, Args_... args);
  std::string* mutable_label();
  PROTOBUF_NODISCARD std::string* release_label();
  void set_allocated_label(std::string* value);

  private:
  const std::string& _internal_label() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_label(
      const std::string& value);
  std::string* _internal_mutable_label();

  public:
  // optional string default_value = 5;
  bool has_default_value() const;
  void clear_default_value() ;
  const std::string& default_value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_default_value(Arg_&& arg, Args_... args);
  std::string* mutable_default_value();
  PROTOBUF_NODISCARD std::string* release_default_value();
  void set_allocated_default_value(std::string* value);

  private:
  const std::string& _internal_default_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_default_value(
      const std::string& value);
  std::string* _internal_mutable_default_value();

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.RecordSpec)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      66, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec > prefix_spec_;
    ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec > suffix_spec_;
    ::google::protobuf::internal::ArenaStringPtr field_path_;
    ::google::protobuf::internal::ArenaStringPtr label_;
    ::google::protobuf::internal::ArenaStringPtr default_value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_5fspec_2eproto;
};// -------------------------------------------------------------------

class StyleSpec final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.StyleSpec) */ {
 public:
  inline StyleSpec() : StyleSpec(nullptr) {}
  ~StyleSpec() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR StyleSpec(::google::protobuf::internal::ConstantInitialized);

  inline StyleSpec(const StyleSpec& from)
      : StyleSpec(nullptr, from) {}
  StyleSpec(StyleSpec&& from) noexcept
    : StyleSpec() {
    *this = ::std::move(from);
  }

  inline StyleSpec& operator=(const StyleSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline StyleSpec& operator=(StyleSpec&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StyleSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const StyleSpec* internal_default_instance() {
    return reinterpret_cast<const StyleSpec*>(
               &_StyleSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StyleSpec& a, StyleSpec& b) {
    a.Swap(&b);
  }
  inline void Swap(StyleSpec* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StyleSpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StyleSpec* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StyleSpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StyleSpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const StyleSpec& from) {
    StyleSpec::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StyleSpec* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.StyleSpec";
  }
  protected:
  explicit StyleSpec(::google::protobuf::Arena* arena);
  StyleSpec(::google::protobuf::Arena* arena, const StyleSpec& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecordSpecFieldNumber = 1,
    kRequiredFieldsFieldNumber = 2,
    kProhibitedFieldsFieldNumber = 3,
  };
  // repeated .speech.sparrowhawk.RecordSpec record_spec = 1;
  int record_spec_size() const;
  private:
  int _internal_record_spec_size() const;

  public:
  void clear_record_spec() ;
  ::speech::sparrowhawk::RecordSpec* mutable_record_spec(int index);
  ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec >*
      mutable_record_spec();
  private:
  const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>& _internal_record_spec() const;
  ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>* _internal_mutable_record_spec();
  public:
  const ::speech::sparrowhawk::RecordSpec& record_spec(int index) const;
  ::speech::sparrowhawk::RecordSpec* add_record_spec();
  const ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec >&
      record_spec() const;
  // repeated string required_fields = 2;
  int required_fields_size() const;
  private:
  int _internal_required_fields_size() const;

  public:
  void clear_required_fields() ;
  const std::string& required_fields(int index) const;
  std::string* mutable_required_fields(int index);
  void set_required_fields(int index, const std::string& value);
  void set_required_fields(int index, std::string&& value);
  void set_required_fields(int index, const char* value);
  void set_required_fields(int index, const char* value, std::size_t size);
  void set_required_fields(int index, absl::string_view value);
  std::string* add_required_fields();
  void add_required_fields(const std::string& value);
  void add_required_fields(std::string&& value);
  void add_required_fields(const char* value);
  void add_required_fields(const char* value, std::size_t size);
  void add_required_fields(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& required_fields() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_required_fields();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_required_fields() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_required_fields();

  public:
  // repeated string prohibited_fields = 3;
  int prohibited_fields_size() const;
  private:
  int _internal_prohibited_fields_size() const;

  public:
  void clear_prohibited_fields() ;
  const std::string& prohibited_fields(int index) const;
  std::string* mutable_prohibited_fields(int index);
  void set_prohibited_fields(int index, const std::string& value);
  void set_prohibited_fields(int index, std::string&& value);
  void set_prohibited_fields(int index, const char* value);
  void set_prohibited_fields(int index, const char* value, std::size_t size);
  void set_prohibited_fields(int index, absl::string_view value);
  std::string* add_prohibited_fields();
  void add_prohibited_fields(const std::string& value);
  void add_prohibited_fields(std::string&& value);
  void add_prohibited_fields(const char* value);
  void add_prohibited_fields(const char* value, std::size_t size);
  void add_prohibited_fields(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& prohibited_fields() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_prohibited_fields();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_prohibited_fields() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_prohibited_fields();

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.StyleSpec)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      69, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::RecordSpec > record_spec_;
    ::google::protobuf::RepeatedPtrField<std::string> required_fields_;
    ::google::protobuf::RepeatedPtrField<std::string> prohibited_fields_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_5fspec_2eproto;
};// -------------------------------------------------------------------

class ClassSpec final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.ClassSpec) */ {
 public:
  inline ClassSpec() : ClassSpec(nullptr) {}
  ~ClassSpec() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ClassSpec(::google::protobuf::internal::ConstantInitialized);

  inline ClassSpec(const ClassSpec& from)
      : ClassSpec(nullptr, from) {}
  ClassSpec(ClassSpec&& from) noexcept
    : ClassSpec() {
    *this = ::std::move(from);
  }

  inline ClassSpec& operator=(const ClassSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClassSpec& operator=(ClassSpec&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClassSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClassSpec* internal_default_instance() {
    return reinterpret_cast<const ClassSpec*>(
               &_ClassSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ClassSpec& a, ClassSpec& b) {
    a.Swap(&b);
  }
  inline void Swap(ClassSpec* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClassSpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClassSpec* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClassSpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClassSpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ClassSpec& from) {
    ClassSpec::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ClassSpec* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.ClassSpec";
  }
  protected:
  explicit ClassSpec(::google::protobuf::Arena* arena);
  ClassSpec(::google::protobuf::Arena* arena, const ClassSpec& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStyleSpecFieldNumber = 2,
    kSemioticClassFieldNumber = 1,
  };
  // repeated .speech.sparrowhawk.StyleSpec style_spec = 2;
  int style_spec_size() const;
  private:
  int _internal_style_spec_size() const;

  public:
  void clear_style_spec() ;
  ::speech::sparrowhawk::StyleSpec* mutable_style_spec(int index);
  ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::StyleSpec >*
      mutable_style_spec();
  private:
  const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::StyleSpec>& _internal_style_spec() const;
  ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::StyleSpec>* _internal_mutable_style_spec();
  public:
  const ::speech::sparrowhawk::StyleSpec& style_spec(int index) const;
  ::speech::sparrowhawk::StyleSpec* add_style_spec();
  const ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::StyleSpec >&
      style_spec() const;
  // optional string semiotic_class = 1;
  bool has_semiotic_class() const;
  void clear_semiotic_class() ;
  const std::string& semiotic_class() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_semiotic_class(Arg_&& arg, Args_... args);
  std::string* mutable_semiotic_class();
  PROTOBUF_NODISCARD std::string* release_semiotic_class();
  void set_allocated_semiotic_class(std::string* value);

  private:
  const std::string& _internal_semiotic_class() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_semiotic_class(
      const std::string& value);
  std::string* _internal_mutable_semiotic_class();

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.ClassSpec)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      51, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::StyleSpec > style_spec_;
    ::google::protobuf::internal::ArenaStringPtr semiotic_class_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_5fspec_2eproto;
};// -------------------------------------------------------------------

class SerializeSpec final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.SerializeSpec) */ {
 public:
  inline SerializeSpec() : SerializeSpec(nullptr) {}
  ~SerializeSpec() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SerializeSpec(::google::protobuf::internal::ConstantInitialized);

  inline SerializeSpec(const SerializeSpec& from)
      : SerializeSpec(nullptr, from) {}
  SerializeSpec(SerializeSpec&& from) noexcept
    : SerializeSpec() {
    *this = ::std::move(from);
  }

  inline SerializeSpec& operator=(const SerializeSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializeSpec& operator=(SerializeSpec&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializeSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializeSpec* internal_default_instance() {
    return reinterpret_cast<const SerializeSpec*>(
               &_SerializeSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SerializeSpec& a, SerializeSpec& b) {
    a.Swap(&b);
  }
  inline void Swap(SerializeSpec* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializeSpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializeSpec* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SerializeSpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializeSpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SerializeSpec& from) {
    SerializeSpec::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SerializeSpec* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.SerializeSpec";
  }
  protected:
  explicit SerializeSpec(::google::protobuf::Arena* arena);
  SerializeSpec(::google::protobuf::Arena* arena, const SerializeSpec& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClassSpecFieldNumber = 1,
  };
  // repeated .speech.sparrowhawk.ClassSpec class_spec = 1;
  int class_spec_size() const;
  private:
  int _internal_class_spec_size() const;

  public:
  void clear_class_spec() ;
  ::speech::sparrowhawk::ClassSpec* mutable_class_spec(int index);
  ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::ClassSpec >*
      mutable_class_spec();
  private:
  const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::ClassSpec>& _internal_class_spec() const;
  ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::ClassSpec>* _internal_mutable_class_spec();
  public:
  const ::speech::sparrowhawk::ClassSpec& class_spec(int index) const;
  ::speech::sparrowhawk::ClassSpec* add_class_spec();
  const ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::ClassSpec >&
      class_spec() const;
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.SerializeSpec)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::speech::sparrowhawk::ClassSpec > class_spec_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_5fspec_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RecordSpec

// repeated .speech.sparrowhawk.RecordSpec prefix_spec = 1;
inline int RecordSpec::_internal_prefix_spec_size() const {
  return _internal_prefix_spec().size();
}
inline int RecordSpec::prefix_spec_size() const {
  return _internal_prefix_spec_size();
}
inline void RecordSpec::clear_prefix_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.prefix_spec_.Clear();
}
inline ::speech::sparrowhawk::RecordSpec* RecordSpec::mutable_prefix_spec(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.RecordSpec.prefix_spec)
  return _internal_mutable_prefix_spec()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>* RecordSpec::mutable_prefix_spec()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.RecordSpec.prefix_spec)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_prefix_spec();
}
inline const ::speech::sparrowhawk::RecordSpec& RecordSpec::prefix_spec(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.RecordSpec.prefix_spec)
  return _internal_prefix_spec().Get(index);
}
inline ::speech::sparrowhawk::RecordSpec* RecordSpec::add_prefix_spec() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::speech::sparrowhawk::RecordSpec* _add = _internal_mutable_prefix_spec()->Add();
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.RecordSpec.prefix_spec)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>& RecordSpec::prefix_spec() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.RecordSpec.prefix_spec)
  return _internal_prefix_spec();
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>&
RecordSpec::_internal_prefix_spec() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.prefix_spec_;
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>*
RecordSpec::_internal_mutable_prefix_spec() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.prefix_spec_;
}

// repeated .speech.sparrowhawk.RecordSpec suffix_spec = 2;
inline int RecordSpec::_internal_suffix_spec_size() const {
  return _internal_suffix_spec().size();
}
inline int RecordSpec::suffix_spec_size() const {
  return _internal_suffix_spec_size();
}
inline void RecordSpec::clear_suffix_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.suffix_spec_.Clear();
}
inline ::speech::sparrowhawk::RecordSpec* RecordSpec::mutable_suffix_spec(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.RecordSpec.suffix_spec)
  return _internal_mutable_suffix_spec()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>* RecordSpec::mutable_suffix_spec()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.RecordSpec.suffix_spec)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_suffix_spec();
}
inline const ::speech::sparrowhawk::RecordSpec& RecordSpec::suffix_spec(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.RecordSpec.suffix_spec)
  return _internal_suffix_spec().Get(index);
}
inline ::speech::sparrowhawk::RecordSpec* RecordSpec::add_suffix_spec() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::speech::sparrowhawk::RecordSpec* _add = _internal_mutable_suffix_spec()->Add();
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.RecordSpec.suffix_spec)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>& RecordSpec::suffix_spec() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.RecordSpec.suffix_spec)
  return _internal_suffix_spec();
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>&
RecordSpec::_internal_suffix_spec() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.suffix_spec_;
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>*
RecordSpec::_internal_mutable_suffix_spec() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.suffix_spec_;
}

// optional string field_path = 3;
inline bool RecordSpec::has_field_path() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void RecordSpec::clear_field_path() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.field_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RecordSpec::field_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.RecordSpec.field_path)
  return _internal_field_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecordSpec::set_field_path(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.field_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.RecordSpec.field_path)
}
inline std::string* RecordSpec::mutable_field_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_field_path();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.RecordSpec.field_path)
  return _s;
}
inline const std::string& RecordSpec::_internal_field_path() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.field_path_.Get();
}
inline void RecordSpec::_internal_set_field_path(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.field_path_.Set(value, GetArena());
}
inline std::string* RecordSpec::_internal_mutable_field_path() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.field_path_.Mutable( GetArena());
}
inline std::string* RecordSpec::release_field_path() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.RecordSpec.field_path)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.field_path_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.field_path_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RecordSpec::set_allocated_field_path(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.field_path_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.field_path_.IsDefault()) {
          _impl_.field_path_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.RecordSpec.field_path)
}

// optional string label = 4;
inline bool RecordSpec::has_label() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void RecordSpec::clear_label() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.label_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RecordSpec::label() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.RecordSpec.label)
  return _internal_label();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecordSpec::set_label(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.label_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.RecordSpec.label)
}
inline std::string* RecordSpec::mutable_label() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.RecordSpec.label)
  return _s;
}
inline const std::string& RecordSpec::_internal_label() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.label_.Get();
}
inline void RecordSpec::_internal_set_label(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.label_.Set(value, GetArena());
}
inline std::string* RecordSpec::_internal_mutable_label() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.label_.Mutable( GetArena());
}
inline std::string* RecordSpec::release_label() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.RecordSpec.label)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.label_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.label_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RecordSpec::set_allocated_label(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.label_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.label_.IsDefault()) {
          _impl_.label_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.RecordSpec.label)
}

// optional string default_value = 5;
inline bool RecordSpec::has_default_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void RecordSpec::clear_default_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.default_value_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& RecordSpec::default_value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.RecordSpec.default_value)
  return _internal_default_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecordSpec::set_default_value(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.default_value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.RecordSpec.default_value)
}
inline std::string* RecordSpec::mutable_default_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_default_value();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.RecordSpec.default_value)
  return _s;
}
inline const std::string& RecordSpec::_internal_default_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.default_value_.Get();
}
inline void RecordSpec::_internal_set_default_value(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.default_value_.Set(value, GetArena());
}
inline std::string* RecordSpec::_internal_mutable_default_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.default_value_.Mutable( GetArena());
}
inline std::string* RecordSpec::release_default_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.RecordSpec.default_value)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.default_value_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.default_value_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RecordSpec::set_allocated_default_value(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.default_value_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.default_value_.IsDefault()) {
          _impl_.default_value_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.RecordSpec.default_value)
}

// -------------------------------------------------------------------

// StyleSpec

// repeated .speech.sparrowhawk.RecordSpec record_spec = 1;
inline int StyleSpec::_internal_record_spec_size() const {
  return _internal_record_spec().size();
}
inline int StyleSpec::record_spec_size() const {
  return _internal_record_spec_size();
}
inline void StyleSpec::clear_record_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.record_spec_.Clear();
}
inline ::speech::sparrowhawk::RecordSpec* StyleSpec::mutable_record_spec(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.StyleSpec.record_spec)
  return _internal_mutable_record_spec()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>* StyleSpec::mutable_record_spec()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.StyleSpec.record_spec)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_record_spec();
}
inline const ::speech::sparrowhawk::RecordSpec& StyleSpec::record_spec(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.StyleSpec.record_spec)
  return _internal_record_spec().Get(index);
}
inline ::speech::sparrowhawk::RecordSpec* StyleSpec::add_record_spec() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::speech::sparrowhawk::RecordSpec* _add = _internal_mutable_record_spec()->Add();
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.StyleSpec.record_spec)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>& StyleSpec::record_spec() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.StyleSpec.record_spec)
  return _internal_record_spec();
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>&
StyleSpec::_internal_record_spec() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.record_spec_;
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::RecordSpec>*
StyleSpec::_internal_mutable_record_spec() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.record_spec_;
}

// repeated string required_fields = 2;
inline int StyleSpec::_internal_required_fields_size() const {
  return _internal_required_fields().size();
}
inline int StyleSpec::required_fields_size() const {
  return _internal_required_fields_size();
}
inline void StyleSpec::clear_required_fields() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.required_fields_.Clear();
}
inline std::string* StyleSpec::add_required_fields()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  std::string* _s = _internal_mutable_required_fields()->Add();
  // @@protoc_insertion_point(field_add_mutable:speech.sparrowhawk.StyleSpec.required_fields)
  return _s;
}
inline const std::string& StyleSpec::required_fields(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.StyleSpec.required_fields)
  return _internal_required_fields().Get(index);
}
inline std::string* StyleSpec::mutable_required_fields(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.StyleSpec.required_fields)
  return _internal_mutable_required_fields()->Mutable(index);
}
inline void StyleSpec::set_required_fields(int index, const std::string& value) {
  _internal_mutable_required_fields()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::set_required_fields(int index, std::string&& value) {
  _internal_mutable_required_fields()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::set_required_fields(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_required_fields()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::set_required_fields(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_required_fields()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::set_required_fields(int index, absl::string_view value) {
  _internal_mutable_required_fields()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::add_required_fields(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_required_fields()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::add_required_fields(std::string&& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_required_fields()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::add_required_fields(const char* value) {
  ABSL_DCHECK(value != nullptr);
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_required_fields()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::add_required_fields(const char* value, std::size_t size) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_required_fields()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:speech.sparrowhawk.StyleSpec.required_fields)
}
inline void StyleSpec::add_required_fields(absl::string_view value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_required_fields()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:speech.sparrowhawk.StyleSpec.required_fields)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
StyleSpec::required_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.StyleSpec.required_fields)
  return _internal_required_fields();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
StyleSpec::mutable_required_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.StyleSpec.required_fields)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_required_fields();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
StyleSpec::_internal_required_fields() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.required_fields_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
StyleSpec::_internal_mutable_required_fields() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.required_fields_;
}

// repeated string prohibited_fields = 3;
inline int StyleSpec::_internal_prohibited_fields_size() const {
  return _internal_prohibited_fields().size();
}
inline int StyleSpec::prohibited_fields_size() const {
  return _internal_prohibited_fields_size();
}
inline void StyleSpec::clear_prohibited_fields() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.prohibited_fields_.Clear();
}
inline std::string* StyleSpec::add_prohibited_fields()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  std::string* _s = _internal_mutable_prohibited_fields()->Add();
  // @@protoc_insertion_point(field_add_mutable:speech.sparrowhawk.StyleSpec.prohibited_fields)
  return _s;
}
inline const std::string& StyleSpec::prohibited_fields(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.StyleSpec.prohibited_fields)
  return _internal_prohibited_fields().Get(index);
}
inline std::string* StyleSpec::mutable_prohibited_fields(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.StyleSpec.prohibited_fields)
  return _internal_mutable_prohibited_fields()->Mutable(index);
}
inline void StyleSpec::set_prohibited_fields(int index, const std::string& value) {
  _internal_mutable_prohibited_fields()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::set_prohibited_fields(int index, std::string&& value) {
  _internal_mutable_prohibited_fields()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::set_prohibited_fields(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_prohibited_fields()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::set_prohibited_fields(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_prohibited_fields()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::set_prohibited_fields(int index, absl::string_view value) {
  _internal_mutable_prohibited_fields()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::add_prohibited_fields(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_prohibited_fields()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::add_prohibited_fields(std::string&& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_prohibited_fields()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::add_prohibited_fields(const char* value) {
  ABSL_DCHECK(value != nullptr);
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_prohibited_fields()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::add_prohibited_fields(const char* value, std::size_t size) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_prohibited_fields()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline void StyleSpec::add_prohibited_fields(absl::string_view value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_prohibited_fields()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:speech.sparrowhawk.StyleSpec.prohibited_fields)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
StyleSpec::prohibited_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.StyleSpec.prohibited_fields)
  return _internal_prohibited_fields();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
StyleSpec::mutable_prohibited_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.StyleSpec.prohibited_fields)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_prohibited_fields();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
StyleSpec::_internal_prohibited_fields() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.prohibited_fields_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
StyleSpec::_internal_mutable_prohibited_fields() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.prohibited_fields_;
}

// -------------------------------------------------------------------

// ClassSpec

// optional string semiotic_class = 1;
inline bool ClassSpec::has_semiotic_class() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ClassSpec::clear_semiotic_class() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.semiotic_class_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ClassSpec::semiotic_class() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.ClassSpec.semiotic_class)
  return _internal_semiotic_class();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ClassSpec::set_semiotic_class(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.semiotic_class_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.ClassSpec.semiotic_class)
}
inline std::string* ClassSpec::mutable_semiotic_class() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_semiotic_class();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.ClassSpec.semiotic_class)
  return _s;
}
inline const std::string& ClassSpec::_internal_semiotic_class() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.semiotic_class_.Get();
}
inline void ClassSpec::_internal_set_semiotic_class(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.semiotic_class_.Set(value, GetArena());
}
inline std::string* ClassSpec::_internal_mutable_semiotic_class() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.semiotic_class_.Mutable( GetArena());
}
inline std::string* ClassSpec::release_semiotic_class() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.ClassSpec.semiotic_class)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.semiotic_class_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.semiotic_class_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ClassSpec::set_allocated_semiotic_class(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.semiotic_class_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.semiotic_class_.IsDefault()) {
          _impl_.semiotic_class_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.ClassSpec.semiotic_class)
}

// repeated .speech.sparrowhawk.StyleSpec style_spec = 2;
inline int ClassSpec::_internal_style_spec_size() const {
  return _internal_style_spec().size();
}
inline int ClassSpec::style_spec_size() const {
  return _internal_style_spec_size();
}
inline void ClassSpec::clear_style_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.style_spec_.Clear();
}
inline ::speech::sparrowhawk::StyleSpec* ClassSpec::mutable_style_spec(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.ClassSpec.style_spec)
  return _internal_mutable_style_spec()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::StyleSpec>* ClassSpec::mutable_style_spec()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.ClassSpec.style_spec)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_style_spec();
}
inline const ::speech::sparrowhawk::StyleSpec& ClassSpec::style_spec(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.ClassSpec.style_spec)
  return _internal_style_spec().Get(index);
}
inline ::speech::sparrowhawk::StyleSpec* ClassSpec::add_style_spec() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::speech::sparrowhawk::StyleSpec* _add = _internal_mutable_style_spec()->Add();
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.ClassSpec.style_spec)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::StyleSpec>& ClassSpec::style_spec() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.ClassSpec.style_spec)
  return _internal_style_spec();
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::StyleSpec>&
ClassSpec::_internal_style_spec() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.style_spec_;
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::StyleSpec>*
ClassSpec::_internal_mutable_style_spec() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.style_spec_;
}

// -------------------------------------------------------------------

// SerializeSpec

// repeated .speech.sparrowhawk.ClassSpec class_spec = 1;
inline int SerializeSpec::_internal_class_spec_size() const {
  return _internal_class_spec().size();
}
inline int SerializeSpec::class_spec_size() const {
  return _internal_class_spec_size();
}
inline void SerializeSpec::clear_class_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.class_spec_.Clear();
}
inline ::speech::sparrowhawk::ClassSpec* SerializeSpec::mutable_class_spec(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.SerializeSpec.class_spec)
  return _internal_mutable_class_spec()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::ClassSpec>* SerializeSpec::mutable_class_spec()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:speech.sparrowhawk.SerializeSpec.class_spec)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_class_spec();
}
inline const ::speech::sparrowhawk::ClassSpec& SerializeSpec::class_spec(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.SerializeSpec.class_spec)
  return _internal_class_spec().Get(index);
}
inline ::speech::sparrowhawk::ClassSpec* SerializeSpec::add_class_spec() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::speech::sparrowhawk::ClassSpec* _add = _internal_mutable_class_spec()->Add();
  // @@protoc_insertion_point(field_add:speech.sparrowhawk.SerializeSpec.class_spec)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::ClassSpec>& SerializeSpec::class_spec() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:speech.sparrowhawk.SerializeSpec.class_spec)
  return _internal_class_spec();
}
inline const ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::ClassSpec>&
SerializeSpec::_internal_class_spec() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.class_spec_;
}
inline ::google::protobuf::RepeatedPtrField<::speech::sparrowhawk::ClassSpec>*
SerializeSpec::_internal_mutable_class_spec() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.class_spec_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sparrowhawk
}  // namespace speech


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_serialization_5fspec_2eproto_2epb_2eh
