// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sparrowhawk_configuration.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_sparrowhawk_5fconfiguration_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_sparrowhawk_5fconfiguration_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_sparrowhawk_5fconfiguration_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_sparrowhawk_5fconfiguration_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_sparrowhawk_5fconfiguration_2eproto;
namespace speech {
namespace sparrowhawk {
class SparrowhawkConfiguration;
struct SparrowhawkConfigurationDefaultTypeInternal;
extern SparrowhawkConfigurationDefaultTypeInternal _SparrowhawkConfiguration_default_instance_;
}  // namespace sparrowhawk
}  // namespace speech
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace speech {
namespace sparrowhawk {

// ===================================================================


// -------------------------------------------------------------------

class SparrowhawkConfiguration final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:speech.sparrowhawk.SparrowhawkConfiguration) */ {
 public:
  inline SparrowhawkConfiguration() : SparrowhawkConfiguration(nullptr) {}
  ~SparrowhawkConfiguration() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SparrowhawkConfiguration(::google::protobuf::internal::ConstantInitialized);

  inline SparrowhawkConfiguration(const SparrowhawkConfiguration& from)
      : SparrowhawkConfiguration(nullptr, from) {}
  SparrowhawkConfiguration(SparrowhawkConfiguration&& from) noexcept
    : SparrowhawkConfiguration() {
    *this = ::std::move(from);
  }

  inline SparrowhawkConfiguration& operator=(const SparrowhawkConfiguration& from) {
    CopyFrom(from);
    return *this;
  }
  inline SparrowhawkConfiguration& operator=(SparrowhawkConfiguration&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SparrowhawkConfiguration& default_instance() {
    return *internal_default_instance();
  }
  static inline const SparrowhawkConfiguration* internal_default_instance() {
    return reinterpret_cast<const SparrowhawkConfiguration*>(
               &_SparrowhawkConfiguration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SparrowhawkConfiguration& a, SparrowhawkConfiguration& b) {
    a.Swap(&b);
  }
  inline void Swap(SparrowhawkConfiguration* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SparrowhawkConfiguration* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SparrowhawkConfiguration* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SparrowhawkConfiguration>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SparrowhawkConfiguration& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SparrowhawkConfiguration& from) {
    SparrowhawkConfiguration::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SparrowhawkConfiguration* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "speech.sparrowhawk.SparrowhawkConfiguration";
  }
  protected:
  explicit SparrowhawkConfiguration(::google::protobuf::Arena* arena);
  SparrowhawkConfiguration(::google::protobuf::Arena* arena, const SparrowhawkConfiguration& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenizerGrammarFieldNumber = 1,
    kVerbalizerGrammarFieldNumber = 2,
    kSentenceBoundaryRegexpFieldNumber = 3,
    kSentenceBoundaryExceptionsFileFieldNumber = 4,
    kSerializationSpecFieldNumber = 5,
  };
  // optional string tokenizer_grammar = 1;
  bool has_tokenizer_grammar() const;
  void clear_tokenizer_grammar() ;
  const std::string& tokenizer_grammar() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tokenizer_grammar(Arg_&& arg, Args_... args);
  std::string* mutable_tokenizer_grammar();
  PROTOBUF_NODISCARD std::string* release_tokenizer_grammar();
  void set_allocated_tokenizer_grammar(std::string* value);

  private:
  const std::string& _internal_tokenizer_grammar() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tokenizer_grammar(
      const std::string& value);
  std::string* _internal_mutable_tokenizer_grammar();

  public:
  // optional string verbalizer_grammar = 2;
  bool has_verbalizer_grammar() const;
  void clear_verbalizer_grammar() ;
  const std::string& verbalizer_grammar() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_verbalizer_grammar(Arg_&& arg, Args_... args);
  std::string* mutable_verbalizer_grammar();
  PROTOBUF_NODISCARD std::string* release_verbalizer_grammar();
  void set_allocated_verbalizer_grammar(std::string* value);

  private:
  const std::string& _internal_verbalizer_grammar() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verbalizer_grammar(
      const std::string& value);
  std::string* _internal_mutable_verbalizer_grammar();

  public:
  // optional string sentence_boundary_regexp = 3;
  bool has_sentence_boundary_regexp() const;
  void clear_sentence_boundary_regexp() ;
  const std::string& sentence_boundary_regexp() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sentence_boundary_regexp(Arg_&& arg, Args_... args);
  std::string* mutable_sentence_boundary_regexp();
  PROTOBUF_NODISCARD std::string* release_sentence_boundary_regexp();
  void set_allocated_sentence_boundary_regexp(std::string* value);

  private:
  const std::string& _internal_sentence_boundary_regexp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sentence_boundary_regexp(
      const std::string& value);
  std::string* _internal_mutable_sentence_boundary_regexp();

  public:
  // optional string sentence_boundary_exceptions_file = 4;
  bool has_sentence_boundary_exceptions_file() const;
  void clear_sentence_boundary_exceptions_file() ;
  const std::string& sentence_boundary_exceptions_file() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sentence_boundary_exceptions_file(Arg_&& arg, Args_... args);
  std::string* mutable_sentence_boundary_exceptions_file();
  PROTOBUF_NODISCARD std::string* release_sentence_boundary_exceptions_file();
  void set_allocated_sentence_boundary_exceptions_file(std::string* value);

  private:
  const std::string& _internal_sentence_boundary_exceptions_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sentence_boundary_exceptions_file(
      const std::string& value);
  std::string* _internal_mutable_sentence_boundary_exceptions_file();

  public:
  // optional string serialization_spec = 5;
  bool has_serialization_spec() const;
  void clear_serialization_spec() ;
  const std::string& serialization_spec() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_serialization_spec(Arg_&& arg, Args_... args);
  std::string* mutable_serialization_spec();
  PROTOBUF_NODISCARD std::string* release_serialization_spec();
  void set_allocated_serialization_spec(std::string* value);

  private:
  const std::string& _internal_serialization_spec() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serialization_spec(
      const std::string& value);
  std::string* _internal_mutable_serialization_spec();

  public:
  // @@protoc_insertion_point(class_scope:speech.sparrowhawk.SparrowhawkConfiguration)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      162, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr tokenizer_grammar_;
    ::google::protobuf::internal::ArenaStringPtr verbalizer_grammar_;
    ::google::protobuf::internal::ArenaStringPtr sentence_boundary_regexp_;
    ::google::protobuf::internal::ArenaStringPtr sentence_boundary_exceptions_file_;
    ::google::protobuf::internal::ArenaStringPtr serialization_spec_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sparrowhawk_5fconfiguration_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SparrowhawkConfiguration

// optional string tokenizer_grammar = 1;
inline bool SparrowhawkConfiguration::has_tokenizer_grammar() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SparrowhawkConfiguration::clear_tokenizer_grammar() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tokenizer_grammar_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SparrowhawkConfiguration::tokenizer_grammar() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.SparrowhawkConfiguration.tokenizer_grammar)
  return _internal_tokenizer_grammar();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SparrowhawkConfiguration::set_tokenizer_grammar(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.tokenizer_grammar_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.SparrowhawkConfiguration.tokenizer_grammar)
}
inline std::string* SparrowhawkConfiguration::mutable_tokenizer_grammar() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_tokenizer_grammar();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.SparrowhawkConfiguration.tokenizer_grammar)
  return _s;
}
inline const std::string& SparrowhawkConfiguration::_internal_tokenizer_grammar() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tokenizer_grammar_.Get();
}
inline void SparrowhawkConfiguration::_internal_set_tokenizer_grammar(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.tokenizer_grammar_.Set(value, GetArena());
}
inline std::string* SparrowhawkConfiguration::_internal_mutable_tokenizer_grammar() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.tokenizer_grammar_.Mutable( GetArena());
}
inline std::string* SparrowhawkConfiguration::release_tokenizer_grammar() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.SparrowhawkConfiguration.tokenizer_grammar)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.tokenizer_grammar_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.tokenizer_grammar_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SparrowhawkConfiguration::set_allocated_tokenizer_grammar(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.tokenizer_grammar_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.tokenizer_grammar_.IsDefault()) {
          _impl_.tokenizer_grammar_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.SparrowhawkConfiguration.tokenizer_grammar)
}

// optional string verbalizer_grammar = 2;
inline bool SparrowhawkConfiguration::has_verbalizer_grammar() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SparrowhawkConfiguration::clear_verbalizer_grammar() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.verbalizer_grammar_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SparrowhawkConfiguration::verbalizer_grammar() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.SparrowhawkConfiguration.verbalizer_grammar)
  return _internal_verbalizer_grammar();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SparrowhawkConfiguration::set_verbalizer_grammar(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.verbalizer_grammar_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.SparrowhawkConfiguration.verbalizer_grammar)
}
inline std::string* SparrowhawkConfiguration::mutable_verbalizer_grammar() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_verbalizer_grammar();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.SparrowhawkConfiguration.verbalizer_grammar)
  return _s;
}
inline const std::string& SparrowhawkConfiguration::_internal_verbalizer_grammar() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.verbalizer_grammar_.Get();
}
inline void SparrowhawkConfiguration::_internal_set_verbalizer_grammar(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.verbalizer_grammar_.Set(value, GetArena());
}
inline std::string* SparrowhawkConfiguration::_internal_mutable_verbalizer_grammar() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.verbalizer_grammar_.Mutable( GetArena());
}
inline std::string* SparrowhawkConfiguration::release_verbalizer_grammar() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.SparrowhawkConfiguration.verbalizer_grammar)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.verbalizer_grammar_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.verbalizer_grammar_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SparrowhawkConfiguration::set_allocated_verbalizer_grammar(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.verbalizer_grammar_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.verbalizer_grammar_.IsDefault()) {
          _impl_.verbalizer_grammar_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.SparrowhawkConfiguration.verbalizer_grammar)
}

// optional string sentence_boundary_regexp = 3;
inline bool SparrowhawkConfiguration::has_sentence_boundary_regexp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SparrowhawkConfiguration::clear_sentence_boundary_regexp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sentence_boundary_regexp_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& SparrowhawkConfiguration::sentence_boundary_regexp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_regexp)
  return _internal_sentence_boundary_regexp();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SparrowhawkConfiguration::set_sentence_boundary_regexp(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.sentence_boundary_regexp_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_regexp)
}
inline std::string* SparrowhawkConfiguration::mutable_sentence_boundary_regexp() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sentence_boundary_regexp();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_regexp)
  return _s;
}
inline const std::string& SparrowhawkConfiguration::_internal_sentence_boundary_regexp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sentence_boundary_regexp_.Get();
}
inline void SparrowhawkConfiguration::_internal_set_sentence_boundary_regexp(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.sentence_boundary_regexp_.Set(value, GetArena());
}
inline std::string* SparrowhawkConfiguration::_internal_mutable_sentence_boundary_regexp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.sentence_boundary_regexp_.Mutable( GetArena());
}
inline std::string* SparrowhawkConfiguration::release_sentence_boundary_regexp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_regexp)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.sentence_boundary_regexp_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sentence_boundary_regexp_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SparrowhawkConfiguration::set_allocated_sentence_boundary_regexp(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.sentence_boundary_regexp_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sentence_boundary_regexp_.IsDefault()) {
          _impl_.sentence_boundary_regexp_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_regexp)
}

// optional string sentence_boundary_exceptions_file = 4;
inline bool SparrowhawkConfiguration::has_sentence_boundary_exceptions_file() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void SparrowhawkConfiguration::clear_sentence_boundary_exceptions_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sentence_boundary_exceptions_file_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& SparrowhawkConfiguration::sentence_boundary_exceptions_file() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_exceptions_file)
  return _internal_sentence_boundary_exceptions_file();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SparrowhawkConfiguration::set_sentence_boundary_exceptions_file(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.sentence_boundary_exceptions_file_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_exceptions_file)
}
inline std::string* SparrowhawkConfiguration::mutable_sentence_boundary_exceptions_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sentence_boundary_exceptions_file();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_exceptions_file)
  return _s;
}
inline const std::string& SparrowhawkConfiguration::_internal_sentence_boundary_exceptions_file() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sentence_boundary_exceptions_file_.Get();
}
inline void SparrowhawkConfiguration::_internal_set_sentence_boundary_exceptions_file(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.sentence_boundary_exceptions_file_.Set(value, GetArena());
}
inline std::string* SparrowhawkConfiguration::_internal_mutable_sentence_boundary_exceptions_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.sentence_boundary_exceptions_file_.Mutable( GetArena());
}
inline std::string* SparrowhawkConfiguration::release_sentence_boundary_exceptions_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_exceptions_file)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.sentence_boundary_exceptions_file_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sentence_boundary_exceptions_file_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SparrowhawkConfiguration::set_allocated_sentence_boundary_exceptions_file(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.sentence_boundary_exceptions_file_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sentence_boundary_exceptions_file_.IsDefault()) {
          _impl_.sentence_boundary_exceptions_file_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.SparrowhawkConfiguration.sentence_boundary_exceptions_file)
}

// optional string serialization_spec = 5;
inline bool SparrowhawkConfiguration::has_serialization_spec() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void SparrowhawkConfiguration::clear_serialization_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.serialization_spec_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& SparrowhawkConfiguration::serialization_spec() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:speech.sparrowhawk.SparrowhawkConfiguration.serialization_spec)
  return _internal_serialization_spec();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SparrowhawkConfiguration::set_serialization_spec(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.serialization_spec_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:speech.sparrowhawk.SparrowhawkConfiguration.serialization_spec)
}
inline std::string* SparrowhawkConfiguration::mutable_serialization_spec() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_serialization_spec();
  // @@protoc_insertion_point(field_mutable:speech.sparrowhawk.SparrowhawkConfiguration.serialization_spec)
  return _s;
}
inline const std::string& SparrowhawkConfiguration::_internal_serialization_spec() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.serialization_spec_.Get();
}
inline void SparrowhawkConfiguration::_internal_set_serialization_spec(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.serialization_spec_.Set(value, GetArena());
}
inline std::string* SparrowhawkConfiguration::_internal_mutable_serialization_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.serialization_spec_.Mutable( GetArena());
}
inline std::string* SparrowhawkConfiguration::release_serialization_spec() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:speech.sparrowhawk.SparrowhawkConfiguration.serialization_spec)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.serialization_spec_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.serialization_spec_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SparrowhawkConfiguration::set_allocated_serialization_spec(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.serialization_spec_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.serialization_spec_.IsDefault()) {
          _impl_.serialization_spec_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:speech.sparrowhawk.SparrowhawkConfiguration.serialization_spec)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sparrowhawk
}  // namespace speech


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_sparrowhawk_5fconfiguration_2eproto_2epb_2eh
